# Generated by Django 3.0.5 on 2020-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_novidade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='novidade',
            name='portal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
