# Generated by Django 3.0.5 on 2020-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_novidade_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novidade',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
