# Generated by Django 3.0.5 on 2020-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200624_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novidade',
            name='titulo',
            field=models.TextField(unique=True),
        ),
        migrations.AlterModelTable(
            name='novidade',
            table='app_novidade',
        ),
    ]
