# Generated by Django 3.0.5 on 2020-08-14 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('palavrasChaves', models.TextField()),
                ('dataInclusao', models.DateField()),
                ('stringBusca', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('especialidade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortalBusca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('dataInclusao', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.TextField()),
                ('pais', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Formato de telefone incorreto.', regex='(\\(?\\d{2,4}\\)?\\s)?(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-\\d{4})')])),
                ('data_nascimento', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Novidade2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPrimeiroAcesso', models.DateField(auto_now_add=True)),
                ('idioma', models.TextField()),
                ('resumo', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('portal', models.CharField(blank=True, max_length=255)),
                ('autores', models.TextField(blank=True)),
                ('fonte', models.URLField()),
                ('link_externo', models.URLField(blank=True)),
                ('jornal', models.TextField(blank=True)),
                ('titulo', models.TextField(unique=True)),
                ('categoria', models.TextField(blank=True)),
                ('data_publicacao', models.TextField(blank=True)),
                ('credibilidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.Credibilidade')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.Especialista')),
                ('portalBusca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.PortalBusca')),
            ],
            options={
                'db_table': 'app_novidade2',
            },
        ),
        migrations.CreateModel(
            name='AvisoPorEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicialRecebim', models.DateField()),
                ('dataFinalRecebim', models.DateField()),
                ('poisNovidade', models.TextField()),
                ('assuntoAviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Assunto')),
                ('credibilidadeAviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Credibilidade')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Pesquisador')),
            ],
        ),
        migrations.AddField(
            model_name='assunto',
            name='novidade',
            field=models.ManyToManyField(to='app2.Novidade2'),
        ),
    ]
