# Generated by Django 3.0.5 on 2020-08-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0005_auto_20200828_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisoporemail',
            old_name='dataFinalRecebim',
            new_name='dataPrimeiroEnvio',
        ),
        migrations.RenameField(
            model_name='avisoporemail',
            old_name='dataInicialRecebim',
            new_name='dataUltimoEnvio',
        ),
        migrations.RenameField(
            model_name='avisoporemail',
            old_name='poisNovidade',
            new_name='frequencia',
        ),
        migrations.RemoveField(
            model_name='avisoporemail',
            name='credibilidadeAviso',
        ),
        migrations.RemoveField(
            model_name='avisoporemail',
            name='pesquisador',
        ),
        migrations.RemoveField(
            model_name='novidade2',
            name='credibilidade',
        ),
        migrations.RemoveField(
            model_name='novidade2',
            name='especialista',
        ),
        migrations.AddField(
            model_name='avisoporemail',
            name='user_alerta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avisoporemail',
            name='assuntoAviso',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Credibilidade',
        ),
        migrations.DeleteModel(
            name='Especialista',
        ),
        migrations.DeleteModel(
            name='Pesquisador',
        ),
    ]
