# Generated by Django 3.0.5 on 2020-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20200828_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisoporemail',
            name='nome',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
