# Generated by Django 3.0.5 on 2020-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20200901_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisoporemail',
            name='dataPrimeiroEnvio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='avisoporemail',
            name='dataUltimoEnvio',
            field=models.DateField(null=True),
        ),
    ]
